
package com.vasu.learning.jax_ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdderImplService", targetNamespace = "http://jax_ws.learning.vasu.com/", wsdlLocation = "http://localhost:8080/jax-ws-0.0.1-SNAPSHOT/AdderImplService?wsdl")
public class AdderImplService
    extends Service
{

    private final static URL ADDERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDERIMPLSERVICE_EXCEPTION;
    private final static QName ADDERIMPLSERVICE_QNAME = new QName("http://jax_ws.learning.vasu.com/", "AdderImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jax-ws-0.0.1-SNAPSHOT/AdderImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDERIMPLSERVICE_WSDL_LOCATION = url;
        ADDERIMPLSERVICE_EXCEPTION = e;
    }

    public AdderImplService() {
        super(__getWsdlLocation(), ADDERIMPLSERVICE_QNAME);
    }

    public AdderImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDERIMPLSERVICE_QNAME, features);
    }

    public AdderImplService(URL wsdlLocation) {
        super(wsdlLocation, ADDERIMPLSERVICE_QNAME);
    }

    public AdderImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDERIMPLSERVICE_QNAME, features);
    }

    public AdderImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdderImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Adder
     */
    @WebEndpoint(name = "AdderImplPort")
    public Adder getAdderImplPort() {
        return super.getPort(new QName("http://jax_ws.learning.vasu.com/", "AdderImplPort"), Adder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Adder
     */
    @WebEndpoint(name = "AdderImplPort")
    public Adder getAdderImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jax_ws.learning.vasu.com/", "AdderImplPort"), Adder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDERIMPLSERVICE_EXCEPTION!= null) {
            throw ADDERIMPLSERVICE_EXCEPTION;
        }
        return ADDERIMPLSERVICE_WSDL_LOCATION;
    }

}
