
package com.vasu.learning.jax_ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Adder", targetNamespace = "http://jax_ws.learning.vasu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Adder {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://jax_ws.learning.vasu.com/", className = "com.vasu.learning.jax_ws.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://jax_ws.learning.vasu.com/", className = "com.vasu.learning.jax_ws.client.AddResponse")
    @Action(input = "http://jax_ws.learning.vasu.com/Adder/addRequest", output = "http://jax_ws.learning.vasu.com/Adder/addResponse")
    public long add(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1);

}
